name: CI Pipeline - Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Basic Flask App Check
        run: |
          python app/main.py &  # run in background
          sleep 5
          curl --fail http://localhost:5000 || exit 1

      - name: Docker Build
        run: |
          docker build -t flask-cicd-app .
